### ISSUE TITLE
Content needed

### ISSUE THREAD

**Issue by Swader** [diffbot/docs#48]
> Diffbot should have an example website hosted with a homepage and some links, a login form behind which some more links sit, a page with JS-generated links, and the ability to add more pages for demos in tutorials (i.e. a page with broken images). That would make writing the content below much easier.

- [x] Recipe: guides-custom-headers-api, using custom headers in direct APIs (done in #46)
- [x] Recipe: guides-custom-headers-crawl, using custom headers in crawl and bulk (done in #46, could be more verbose on real reproducible example)
- [x] Tutorial on using X-Evaluate, preferably on a reproducible Diffbot-hosted page (done in #46)
